import React from 'react'

const contact = () => {
  return (
    <div>
      this is my contact page .
    </div>
  )
}

export default contact


export const metadata = {
  title: "Contact page",
  description: "Generated by Rustam.",
};
