import React from 'react'

const about = () => {
  return (
    <div>
      this is my about page .
    </div>
  )
}

export default about

export const metadata = {
  title: "About page",
  description: "Generated by Rustam.",
};
